export { default as createAvatar } from './createAvatar'
export { default as deleteAvatar } from './deleteAvatar'
export { default as getAllUsers } from './getAllUsers'
export { default as getAvatarThumbnail } from './getAvatarThumbnail'
export { default as getOriginalAvatar } from './getOriginalAvatar'
export { default as getUser } from './getUser'
export { default as getUserById } from './getUserById'
export { default as updateAvatarThumbnail } from './updateAvatarThumbnail'
export * from './updateUser'
export { default as updateUser } from './updateUser'
